name: zawgyi_converter
description: Zawgyi <-> Unicode Converter. Three functions are supported for now 1. unicodeToZawgyi, 2. zawgyiToUnicode, 3. normalizeZawgyi
version: 0.0.4+pre-v0.1
author: Thura Aung <thura.ucsy@gmail.com>
homepage: https://github.com/thuraucsy/zawgyi_converter

environment:
  sdk: ">=2.1.0 <3.0.0"